from .PIP_ColorPicker import NODE_CLASS_MAPPINGS as PIP_COLOR_PICKER_NODE_CLASS_MAPPINGS
from .PIP_ColorPicker import NODE_DISPLAY_NAME_MAPPINGS as PIP_COLOR_PICKER_NODE_DISPLAY_NAME_MAPPINGS
from .PIP_AdvancedColorAnalyzer import NODE_CLASS_MAPPINGS as PIP_ADVANCED_COLOR_ANALYZER_NODE_CLASS_MAPPINGS
from .PIP_AdvancedColorAnalyzer import NODE_DISPLAY_NAME_MAPPINGS as PIP_ADVANCED_COLOR_ANALYZER_NODE_DISPLAY_NAME_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **PIP_COLOR_PICKER_NODE_CLASS_MAPPINGS,
    **PIP_ADVANCED_COLOR_ANALYZER_NODE_CLASS_MAPPINGS,
}

# 合并所有显示名称映射
NODE_DISPLAY_NAME_MAPPINGS = {
    **PIP_COLOR_PICKER_NODE_DISPLAY_NAME_MAPPINGS,
    **PIP_ADVANCED_COLOR_ANALYZER_NODE_DISPLAY_NAME_MAPPINGS,
}
